//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Inputs/MenuInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Inputs/MenuInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MenuInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MenuInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MenuInputActions"",
    ""maps"": [
        {
            ""name"": ""UI_Controls"",
            ""id"": ""489f7839-c308-4ff8-8e1b-8eaee4d951b2"",
            ""actions"": [
                {
                    ""name"": ""Open_Menu"",
                    ""type"": ""Button"",
                    ""id"": ""74c01857-f1a7-4197-869d-a6d7e0cc8731"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_1"",
                    ""type"": ""Button"",
                    ""id"": ""ecd475a5-7352-450f-bb3e-10043d6d92df"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_2"",
                    ""type"": ""Button"",
                    ""id"": ""7b3f363b-4cd1-4d44-ad0b-08ae0420ab1e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_3"",
                    ""type"": ""Button"",
                    ""id"": ""22d9ecd0-3178-4ce7-9dc7-d6f312225be0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_4"",
                    ""type"": ""Button"",
                    ""id"": ""1d1af1f9-ad2a-4f87-8c7f-023ff15cb421"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_5"",
                    ""type"": ""Button"",
                    ""id"": ""66a5e240-bdb6-4985-98db-8e0515846e65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_6"",
                    ""type"": ""Button"",
                    ""id"": ""cbc6ecd7-26b2-49df-bb05-5e9c363227de"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_7"",
                    ""type"": ""Button"",
                    ""id"": ""14e5c408-cfaa-48d1-a5bd-84b4e024193a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_8"",
                    ""type"": ""Button"",
                    ""id"": ""528dadb0-0e12-4345-b311-ea685f4dd051"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSlot_9"",
                    ""type"": ""Button"",
                    ""id"": ""4fdef348-f733-4bac-8ca2-fc49ea290898"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b912903d-cfa9-4ed3-b229-23ccd751e7ad"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open_Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bc348a5-2ed2-42e7-b1b7-0860e60059fb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ebfbdec-4eca-4677-bd76-1f9e1a1ed9d9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dda5befd-11f4-4637-95f9-2b3e13e74fe4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b4115a2-4ce8-449b-9163-6a342eb9af17"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1a856d7-c45e-454d-b9d1-923fdfc24b16"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""202f08c8-3abb-40cd-befc-54ebf4851a54"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c92f1450-f893-4c0c-9fb6-17a8745cbe84"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c02eae65-4c62-4f05-9104-d872ec1a505c"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed3de045-c2f5-4376-9905-243c64e925d9"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSlot_9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI_Controls
        m_UI_Controls = asset.FindActionMap("UI_Controls", throwIfNotFound: true);
        m_UI_Controls_Open_Menu = m_UI_Controls.FindAction("Open_Menu", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_1 = m_UI_Controls.FindAction("SelectSlot_1", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_2 = m_UI_Controls.FindAction("SelectSlot_2", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_3 = m_UI_Controls.FindAction("SelectSlot_3", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_4 = m_UI_Controls.FindAction("SelectSlot_4", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_5 = m_UI_Controls.FindAction("SelectSlot_5", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_6 = m_UI_Controls.FindAction("SelectSlot_6", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_7 = m_UI_Controls.FindAction("SelectSlot_7", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_8 = m_UI_Controls.FindAction("SelectSlot_8", throwIfNotFound: true);
        m_UI_Controls_SelectSlot_9 = m_UI_Controls.FindAction("SelectSlot_9", throwIfNotFound: true);
    }

    ~@MenuInputActions()
    {
        UnityEngine.Debug.Assert(!m_UI_Controls.enabled, "This will cause a leak and performance issues, MenuInputActions.UI_Controls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI_Controls
    private readonly InputActionMap m_UI_Controls;
    private List<IUI_ControlsActions> m_UI_ControlsActionsCallbackInterfaces = new List<IUI_ControlsActions>();
    private readonly InputAction m_UI_Controls_Open_Menu;
    private readonly InputAction m_UI_Controls_SelectSlot_1;
    private readonly InputAction m_UI_Controls_SelectSlot_2;
    private readonly InputAction m_UI_Controls_SelectSlot_3;
    private readonly InputAction m_UI_Controls_SelectSlot_4;
    private readonly InputAction m_UI_Controls_SelectSlot_5;
    private readonly InputAction m_UI_Controls_SelectSlot_6;
    private readonly InputAction m_UI_Controls_SelectSlot_7;
    private readonly InputAction m_UI_Controls_SelectSlot_8;
    private readonly InputAction m_UI_Controls_SelectSlot_9;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_Controls".
    /// </summary>
    public struct UI_ControlsActions
    {
        private @MenuInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_ControlsActions(@MenuInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/Open_Menu".
        /// </summary>
        public InputAction @Open_Menu => m_Wrapper.m_UI_Controls_Open_Menu;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_1".
        /// </summary>
        public InputAction @SelectSlot_1 => m_Wrapper.m_UI_Controls_SelectSlot_1;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_2".
        /// </summary>
        public InputAction @SelectSlot_2 => m_Wrapper.m_UI_Controls_SelectSlot_2;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_3".
        /// </summary>
        public InputAction @SelectSlot_3 => m_Wrapper.m_UI_Controls_SelectSlot_3;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_4".
        /// </summary>
        public InputAction @SelectSlot_4 => m_Wrapper.m_UI_Controls_SelectSlot_4;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_5".
        /// </summary>
        public InputAction @SelectSlot_5 => m_Wrapper.m_UI_Controls_SelectSlot_5;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_6".
        /// </summary>
        public InputAction @SelectSlot_6 => m_Wrapper.m_UI_Controls_SelectSlot_6;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_7".
        /// </summary>
        public InputAction @SelectSlot_7 => m_Wrapper.m_UI_Controls_SelectSlot_7;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_8".
        /// </summary>
        public InputAction @SelectSlot_8 => m_Wrapper.m_UI_Controls_SelectSlot_8;
        /// <summary>
        /// Provides access to the underlying input action "UI_Controls/SelectSlot_9".
        /// </summary>
        public InputAction @SelectSlot_9 => m_Wrapper.m_UI_Controls_SelectSlot_9;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_Controls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_ControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_ControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_ControlsActions" />
        public void AddCallbacks(IUI_ControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_ControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_ControlsActionsCallbackInterfaces.Add(instance);
            @Open_Menu.started += instance.OnOpen_Menu;
            @Open_Menu.performed += instance.OnOpen_Menu;
            @Open_Menu.canceled += instance.OnOpen_Menu;
            @SelectSlot_1.started += instance.OnSelectSlot_1;
            @SelectSlot_1.performed += instance.OnSelectSlot_1;
            @SelectSlot_1.canceled += instance.OnSelectSlot_1;
            @SelectSlot_2.started += instance.OnSelectSlot_2;
            @SelectSlot_2.performed += instance.OnSelectSlot_2;
            @SelectSlot_2.canceled += instance.OnSelectSlot_2;
            @SelectSlot_3.started += instance.OnSelectSlot_3;
            @SelectSlot_3.performed += instance.OnSelectSlot_3;
            @SelectSlot_3.canceled += instance.OnSelectSlot_3;
            @SelectSlot_4.started += instance.OnSelectSlot_4;
            @SelectSlot_4.performed += instance.OnSelectSlot_4;
            @SelectSlot_4.canceled += instance.OnSelectSlot_4;
            @SelectSlot_5.started += instance.OnSelectSlot_5;
            @SelectSlot_5.performed += instance.OnSelectSlot_5;
            @SelectSlot_5.canceled += instance.OnSelectSlot_5;
            @SelectSlot_6.started += instance.OnSelectSlot_6;
            @SelectSlot_6.performed += instance.OnSelectSlot_6;
            @SelectSlot_6.canceled += instance.OnSelectSlot_6;
            @SelectSlot_7.started += instance.OnSelectSlot_7;
            @SelectSlot_7.performed += instance.OnSelectSlot_7;
            @SelectSlot_7.canceled += instance.OnSelectSlot_7;
            @SelectSlot_8.started += instance.OnSelectSlot_8;
            @SelectSlot_8.performed += instance.OnSelectSlot_8;
            @SelectSlot_8.canceled += instance.OnSelectSlot_8;
            @SelectSlot_9.started += instance.OnSelectSlot_9;
            @SelectSlot_9.performed += instance.OnSelectSlot_9;
            @SelectSlot_9.canceled += instance.OnSelectSlot_9;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_ControlsActions" />
        private void UnregisterCallbacks(IUI_ControlsActions instance)
        {
            @Open_Menu.started -= instance.OnOpen_Menu;
            @Open_Menu.performed -= instance.OnOpen_Menu;
            @Open_Menu.canceled -= instance.OnOpen_Menu;
            @SelectSlot_1.started -= instance.OnSelectSlot_1;
            @SelectSlot_1.performed -= instance.OnSelectSlot_1;
            @SelectSlot_1.canceled -= instance.OnSelectSlot_1;
            @SelectSlot_2.started -= instance.OnSelectSlot_2;
            @SelectSlot_2.performed -= instance.OnSelectSlot_2;
            @SelectSlot_2.canceled -= instance.OnSelectSlot_2;
            @SelectSlot_3.started -= instance.OnSelectSlot_3;
            @SelectSlot_3.performed -= instance.OnSelectSlot_3;
            @SelectSlot_3.canceled -= instance.OnSelectSlot_3;
            @SelectSlot_4.started -= instance.OnSelectSlot_4;
            @SelectSlot_4.performed -= instance.OnSelectSlot_4;
            @SelectSlot_4.canceled -= instance.OnSelectSlot_4;
            @SelectSlot_5.started -= instance.OnSelectSlot_5;
            @SelectSlot_5.performed -= instance.OnSelectSlot_5;
            @SelectSlot_5.canceled -= instance.OnSelectSlot_5;
            @SelectSlot_6.started -= instance.OnSelectSlot_6;
            @SelectSlot_6.performed -= instance.OnSelectSlot_6;
            @SelectSlot_6.canceled -= instance.OnSelectSlot_6;
            @SelectSlot_7.started -= instance.OnSelectSlot_7;
            @SelectSlot_7.performed -= instance.OnSelectSlot_7;
            @SelectSlot_7.canceled -= instance.OnSelectSlot_7;
            @SelectSlot_8.started -= instance.OnSelectSlot_8;
            @SelectSlot_8.performed -= instance.OnSelectSlot_8;
            @SelectSlot_8.canceled -= instance.OnSelectSlot_8;
            @SelectSlot_9.started -= instance.OnSelectSlot_9;
            @SelectSlot_9.performed -= instance.OnSelectSlot_9;
            @SelectSlot_9.canceled -= instance.OnSelectSlot_9;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_ControlsActions.UnregisterCallbacks(IUI_ControlsActions)" />.
        /// </summary>
        /// <seealso cref="UI_ControlsActions.UnregisterCallbacks(IUI_ControlsActions)" />
        public void RemoveCallbacks(IUI_ControlsActions instance)
        {
            if (m_Wrapper.m_UI_ControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_ControlsActions.AddCallbacks(IUI_ControlsActions)" />
        /// <seealso cref="UI_ControlsActions.RemoveCallbacks(IUI_ControlsActions)" />
        /// <seealso cref="UI_ControlsActions.UnregisterCallbacks(IUI_ControlsActions)" />
        public void SetCallbacks(IUI_ControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_ControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_ControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_ControlsActions" /> instance referencing this action map.
    /// </summary>
    public UI_ControlsActions @UI_Controls => new UI_ControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_Controls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_ControlsActions.AddCallbacks(IUI_ControlsActions)" />
    /// <seealso cref="UI_ControlsActions.RemoveCallbacks(IUI_ControlsActions)" />
    public interface IUI_ControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Open_Menu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpen_Menu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSlot_9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSlot_9(InputAction.CallbackContext context);
    }
}
